# Generated by Django 3.2.5 on 2021-09-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Identification', models.IntegerField()),
                ('Contact', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Identification', models.IntegerField()),
                ('Contact', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Identification', models.IntegerField()),
                ('Contact', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
